---
title: "Leaflet"
author: "Paul Bruynel"
date: "12 July 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## My first map with Leaflet
```{r, echo=FALSE}
library(leaflet)
my_map <- leaflet() %>%
  addTiles()
my_map
```

## Add markers
```{r}
martiniToren <- c(53.21955619718622, 6.5680924402408785)
my_map <- my_map %>%
  addMarkers(lat = martiniToren[1], lng = martiniToren[2],
             popup = "Martini toren, Groningen")
my_map
```

## Add multiple markers
```{r}
df <- data.frame(lat = runif(20, min=martiniToren[1] - 0.1, max=martiniToren[1] + 0.1),
                 lng = runif(20, min=martiniToren[2] - 0.1, max=martiniToren[2] + 0.1))
df %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(popup = paste(martiniToren[1], martiniToren[2]))
```

## Making Custom Markers

The blue markers that leaflet comes packaged with may not be
enough depending on what you're mapping. Thankfully you can
make your own markers from `.png` files.

```{r}
triventoIcon <- makeIcon(
  iconUrl = "https://www.trivento.nl/hubfs/Website-2020/img/trivlogo.png",
  iconWidth = 50, iconHeight = 50 * (585/1200),
  #iconWidth = 31*215/230, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16
)

triventoLatLong <- data.frame(
  lat = c(52.1965808530428),
  lng = c(5.398014240571794))

triventoSite <- "<a href='https://www.trivento.nl/'>Trivento</a>"

triventoLatLong %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = triventoIcon, popup = triventoSite)

```